name: GIPHY generator

on:
  issues:
    types: [opened, edited]
  pull-request:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  giphy-generator:
    runs-on: ubuntu-latest
    
    steps: 
      - name: GIPHY Generator
        uses: IAmHughes/giphy-generator@v1.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB__TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY__TOKEN }}
        with:
          rating: 'g'
          lang: 'en'
